org.gradle.jvmargs=-Xmx1G

# https://fabricmc.net/develop/
minecraft_version=26.3-rc-2
minecraft_compat_version=26.3.x

loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=0.8.3+26.3
maven_group=dev.doublekekse
archives_base_name=area_lib

# Dependencies
fabric_api_version=0.160.3+26.3
